name: deploy new build
on:
  push:
    paths:
      - .output/**
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: clone and copy new build
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: jg-pwa
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/jg-pwa/GitHub/jg-pwa
          git pull
    - name: restart node server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: systemctl restart jg-pwa
