name: remote ssh command
on:
  push:
    paths:
      - .output/**
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/jg-pwa/GitHub/jg-pwa
          git pull
          cp .output /home/jg-pwa -r
          systemctl restart jg-pwa
